import { Currency, Flag, Store } from "@/types/store";

export const STORE: Store = {
  address: "",
  city: "Mazatlán",
  country: {
    calling_code: "52",
    currency: Currency.MXPeso,
    currency_symbol: "$",
    flag: Flag.USPNG,
    id: 1,
    name: "Empowerit TOP",
  },
  country_id: 1,
  created_at: new Date(),
  created_by_id: "1",
  deleted_at: null,
  description: "",
  facebook: null,
  hide_vendor_email: 0,
  hide_vendor_phone: 0,
  id: 1,
  instagram: null,
  is_approved: 1,
  order_amount: 0,
  orders_count: 0,
  pincode: "",
  pinterest: null,
  product_images: [],
  products_count: 0,
  rating_count: 0,
  reviews: [],
  reviews_count: 0,
  slug: "",
  state: {
    id: 1,
    name: "Sinaloa",
    country_id: "1",
    created_at: new Date(),
    updated_at: new Date(),
  },
  state_id: 1,
  status: 1,
  store_cover: null,
  store_cover_id: 1,
  store_logo: {
    name: "Logo",
    original_url: "https://react.pixelstrap.net/fastkart/assets/logo.png",
  },
  store_logo_id: 1,
  store_name: "Empowerit TOP",
  twitter: "",
  updated_at: new Date(),
  vendor: null,
  vendor_id: 1,
  youtube: "",
};
